name: develop nnblog ui
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Deploy'
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.REMOTE_HOST}}
          username: ${{ secrets.REMOTE_USERNAME }} # 登陆服务器的用户名
          key: ${{ secrets.PRIVATE_KEY }} # 登陆服务器的密钥
          source: "./src"
          target: "/opt/actions"
